Update helper functions
I also removed the --snapdhot-dir option as it was not needed. I use the
second positional argument now.

diff --git a/dsnapshot b/dsnapshot
--- a/dsnapshot
+++ b/dsnapshot
@@ -5,6 +5,16 @@
 #
 # See DESCRIPTION below in print_help(), or run dsnapshot --help
 #
+# Note on exit codes:
+#
+#   Some shell programmers use the exit codes defined in
+#   /usr/include/asm-generic/errno.h. Some use the codes defined in
+#   /usr/include/sysexits.h. Others
+#   (http://tldp.org/LDP/abs/html/exitcodes.html) try to avoid those codes.
+#   This program uses the codes defined in /usr/include/sysexits.h if
+#   applicable, other codes from 79–113 if needed, or the generic 0 for success
+#   and 1 for failure.
+#
 
 function main
 {
@@ -15,7 +25,7 @@ function main
     export snapshot_dir=''
 
 
-    parse_args "${@}"
+    parse_opts "${@}"
 
 
     # Determine which config file template to use.
@@ -102,12 +112,13 @@ function print_help
 		    volume.
 		
 		OPTIONS
+		    -c WHEN, --color=WHEN
+		        Colorize the output. WHEN can be 'always', 'auto' (default if
+		        omitted), or 'never'. With 'auto' it emits color codes only
+		        when standard output is connected to a terminal.
+		
 		    -s, --source-dir
 		        The directory to make snapshots of.
-		
-		    -d, --snapshot-dir
-		        The directory to make the snapshots in. Defaults to a directory named
-		        'snapshots' in the same directory as the source directory.
 		
 		    -d, --debug
 		        Enable debug output.
@@ -122,11 +133,18 @@ function print_help
 		    dsnapshot /home/fred/Documents /home/fred/backup/Documents
 		
 		    dsnapshot /srv/backup/users/fred/music/latest /srv/backup/users/fred/music/snapshots
+		
+		EXIT CODES
+		    0  Success
+		    1  Error
+		    64 Command line usage error
+		
+		    Some exit codes based on /usr/include/sysexits.h
 	EOF
 }
 
 
-function parse_args
+function parse_opts
 {
     #
     # Parse the command-line arguments.
@@ -139,7 +157,7 @@ function parse_args
     if [[ ${PIPESTATUS[0]} -ne 4 ]]
     then
         die 'I’m sorry, cannot parse command line parameters in this environment. `getopt --test` failed.'
-        exit 1
+        exit 71
     fi
 
     #
@@ -150,8 +168,8 @@ function parse_args
     #   OPTIONS=s:dt
     #   LONGOPTS=source:,debug,test
     #
-    OPTIONS=dth
-    LONGOPTS=debug,test,help
+    OPTIONS=c:dth
+    LONGOPTS=color:,debug,test,help
 
     # Use ! and PIPESTATUS to get exit code with errexit set.
     # Temporarily store output to be able to check for errors.
@@ -162,12 +180,15 @@ function parse_args
     then
         # e.g. return value is 1
         #  then getopt has complained about wrong arguments to stdout
-        exit 2
+        exit 70
     fi
     # read getopt’s output this way to handle the quoting right:
     eval set -- "$PARSED"
 
-    path= ratings_file=
+    # Set defaults here or earlier, if any.
+
+    local input_color_option
+
     #
     # Now enjoy the options in order and nicely split until we see --
     #
@@ -178,10 +199,15 @@ function parse_args
     #       shift 2
     #       ;;
     #
-    while true; do
+    while true
+    do
         case "$1" in
+            -c|--color)
+                input_color_option="$2"
+                shift 2
+                ;;
             -d|--debug)
-                export DEBUG=true
+                DEBUG=true
                 shift
                 ;;
             -t|--test)
@@ -191,29 +217,52 @@ function parse_args
             -h|--help)
                 print_help
                 exit
-                shift
                 ;;
             --)
                 shift
                 break
                 ;;
             *)
-                echo "Programming error"
-                exit 3
+                echo "Internal software error"
+                exit 70
                 ;;
         esac
     done
 
 
+    case "${input_color_option}" in
+        always|yes|force)
+            color_option=always
+            ;;
+        never|no|none)
+            color_option=never
+            ;;
+        auto|tty|if-tty)
+            # Defaults to this if unset.
+            color_option=auto
+            ;;
+        '')
+            # Let the color function choose the default.
+            ;;
+        *)
+            alarm "Invalid value ${input_color_option} for --color."
+            echo
+            print_help
+            # "command line usage error" in /usr/include/sysexits.h.
+            exit 64
+            ;;
+    esac
+
+
     if [ -z "${1}" ]
     then
-        die 'ERROR: No source dir specified.'
+        die 'ERROR: No source dir specified.' 64
     fi
     source_dir="${1}"
 
     if [ ! -d "${source_dir}" ]
     then
-        die 'ERROR: Invalid source directory.'
+        die 'ERROR: Invalid source directory.' 64
     fi
     # Ensure source_dir is a fully qualified path with trailing slash.
     source_dir="$(cd "$(dirname "${source_dir}")" && pwd)/$(basename "${source_dir}")/"
@@ -234,7 +283,7 @@ function parse_args
 
 
 #
-# Clean up the temp file.
+# Clean up the temp directory.
 #
 # The trap command ensures this is called upon exit, even if the program exits
 # with an error.
@@ -256,18 +305,67 @@ bool() ([ -z "${2+x}" ] && [[ $1 == true ]])
 
 
 #
+# Returns success (0) if colour should be output and failure (1) otherwise.
+#
+# Usage:
+#
+#   if color; then …; fi
+#
+# Defaults to 'auto' if global $color_option is unset or an empty string.
+#
+# Exits with an error message if global $color_option is an invalid value.
+#
+function color
+{
+    case "${color_option}" in
+        always)
+            return 0
+            ;;
+        never)
+            return 1
+            ;;
+        auto|'')
+            # Output color when stdout is a terminal.
+            if [ -t 1 ]
+            then
+                # stdout is a terminal. Use color output.
+                return 0
+            else
+                # stdout is not a terminal. Do not use color output.
+                return 1
+            fi
+            ;;
+        *)
+            set_color_option="${color_option}"
+            # Set a valid color_option so we can output our error message.
+            color_option=auto
+            die "Internal software error: Invalid color_option: ${set_color_option}." 70
+            ;;
+    esac
+}
+
+
+#
 # warn - print warning message
 #
 # $1 - message
 #
 function warn
 {
-    # print to regular output in regular orange
-    printf "\e[0;33m"
-    # Print the message with `echo` to prevent anything in the string from
-    # being interpreted as formatting characters.
+    if color
+    then
+        # print to regular output in regular orange
+        printf "\033[0;33m"
+    fi
+
+    # Print the message with regular `echo` to prevent anything in the string
+    # from being interpreted as formatting characters.
     echo "${1}"
-    printf "\e[m"
+
+    if color
+    then
+        printf "\033[m"
+    fi
 }
 
 
@@ -278,12 +376,20 @@ function warn
 #
 function alarm
 {
-    # print to error output in bold red
-    printf "\e[1;31m" >&2
-    # Print the message with `echo` to prevent anything in the string from
-    # being interpreted as formatting characters.
+    if color
+    then
+        # print to error output in bold red
+        printf "\033[1;31m" >&2
+    fi
+
+    # Print the message with regular `echo` to prevent anything in the string
+    # from being interpreted as formatting characters.
     echo "${1}" >&2
-    printf "\e[m" >&2
+
+    if color
+    then
+        printf "\033[m" >&2
+    fi
 }
 
 
@@ -382,6 +488,15 @@ function check_directory
     then
         mkdir -p "${1}"
         check_err $? 'Directory ${1} could not be created. Aborting.'
+    fi
+
+    # We check the dir by changing to it. We must change to it in a subshell to
+    # avoid changing the current directory of the calling command.
+    err="$(if ! cd "${1}"; then echo "Cannot access directory ${1}. Aborting."; fi)"
+
+    if [ ! -z "${err}" ]
+    then
+        die "${err}"
     fi
 }
 
